sudo: false
dist: xenial
language: rust
cache:
  cargo: true
  dir: $SCCACHE_DIR

rust:
  - stable
  - beta
  - nightly

env:
  global:
  - RUST_BACKTRACE=1
  - RUSTC_WRAPPER=sccache
  - SCCACHE_DIR="$HOME/.cache/sccache"

before_install:
  - ci/travis/setup.sh

script:
  - cargo test

after_success:
  - cargo tarpaulin
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: cargo publish
  on:
    tags: true
    repo: althonos/obofoundry.rs
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
