name: Test

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check code format
      run: cargo fmt --all -- --check
  test:
    name: Test (${{ matrix.rust-toolchain }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
          - nightly
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Check code
      run: cargo check
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Measure code coverage
      run: cargo tarpaulin -v --out Xml --ciserver github-actions
    - name: Upload coverage statistics
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        flags: rust-${{ matrix.rust-toolchain }}
        verbose: true
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: Crates.io
    needs: test
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@stable
    - name: Package and publish
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: GitHub Releases
    needs: publish
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Update release notes
      uses: rasmus-saks/release-a-changelog-action@v1.2.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
